version: '3.8'
services:
  mongodb:
    container_name: planetdjanet-mongo
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
      MONGO_INITDB_DATABASE: planet_djanet

  
  backend:
    container_name: planetdjanet-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=rootpwd
      - MONGODB_HOSTNAME=planetdjanet-mongo
      - MONGODB_DATABASE=planet_djanet
    depends_on:
      - mongodb

  frontend:
    container_name: planetdjanet-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOSTNAME=planetdjanet-backend
    ports:
      - "8501:8501" 
    depends_on:
      - backend