version: '3.8'
services:
  mongodb:
    container_name: planetdjanet-mongo
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
      MONGO_INITDB_DATABASE: planet_djanet

  frontend:
    container_name: planetdjanet-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501" 
    environment:
      - NODE_ENV=production # Set environment variables if needed
  