version: '3.8'
services:
  mongodb:
    container_name: planetdjanet-mongo
    image: mongo:latest
    build:
      context: ./database
      dockerfile: ./database/Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpwd
      MONGO_INITDB_DATABASE: planet_djanet
    volumes:
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./database/files/posts_1.json:/data/posts_1.json
      - ./database/files/followers.json:/data/followers.json
      - ./database/files/following.json:/data/following.json
      - ./database/files/posts.json:/data/posts.json
      - ./database/files/Tous_les_contenus.csv:/data/Tous_les_contenus.csv
      - ./database/files/Couverture.csv:/data/Couverture.csv
      - ./database/files/Couverture_Insta.csv:/data/Couverture_Insta.csv
      - ./database/files/Visits_Fb.csv:/data/Visits_Fb.csv
      - ./database/files/Visits_Insta.csv:/data/Visits_Insta.csv
      - ./database/files/likes_gender_age.csv:/data/likes_gender_age.csv
      - ./database/files/likes_ville.csv:/data/likes_ville.csv
      - ./database/files/Tendances_publicitaires.csv:/data/Tendances_publicitaires.csv
volumes:
  mongodb_data_container:
  