name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Set the job to run on Ubuntu
    runs-on: ubuntu-latest
  services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpwd
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and run containers
      run: docker-compose up -d

    - name: List running containers
      run: docker ps -a

    - name: Run backend tests
      run: |
        docker exec planetdjanet-backend pytest

    - name: Run frontend tests
      run: |
        docker exec planetdjanet-frontend npm test

    - name: Stop and remove containers
      if: always()
      run: docker-compose down