name: Unit Tests

on: [push]

jobs:
  test_connection_database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip install pytest
    - run: pytest backend/tests/test_mongodb_connection.py

  test_page_meta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip install pandas requests pytest
    - run: pytest frontend/tests/test_meta.py